### ISSUE TITLE
joker: HTTP 414 client error when adding a new record

### ISSUE THREAD

**Issue by nextgens** [AnalogJ/lexicon#1006]
Hi,

I get a "414 Client error" when trying to add a new record to one of my zones hosted at Joker. Is there an easy fix or is that a limitation of their API?

```
lexicon joker create example.com A --name a --content 127.0.0.1
Traceback (most recent call last):
  File "/home/nextgens/src/lexicon/env/bin/lexicon", line 10, in <module>
    sys.exit(main())
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/lexicon/cli.py", line 131, in main
    results = client.execute()
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/lexicon/client.py", line 88, in execute
    return self.provider.create_record(record_type, name, content)
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/lexicon/providers/base.py", line 79, in create_record
    return self._create_record(rtype, name, content)
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/lexicon/providers/joker.py", line 165, in _create_record
    self._apply_zonedata(zonedata)
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/lexicon/providers/joker.py", line 272, in _apply_zonedata
    query_params={"domain": self.domain_id, "zone": "\n".join(data)},
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/lexicon/providers/base.py", line 173, in _get
    return self._request("GET", url, query_params=query_params)
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/lexicon/providers/joker.py", line 97, in _request
    return _process_response(response)
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/lexicon/providers/joker.py", line 354, in _process_response
    response.raise_for_status()
  File "/home/nextgens/src/lexicon/env/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 414 Client Error: Request URI too long for url: https://dmapi.joker.com/request/dns-zone-put?...
```

**Comment by adferrand** [comment]
At first sight, it seems that the Joker API only pass arguments of request as parameters in the URL. Indeed this is a problem since URL size is usually limited. This is the case in this request.

**Comment by nextgens** [comment]
I've just tried using a POST request instead and it seems to work:

![image](https://user-images.githubusercontent.com/77500/141948396-63b6b483-d3c2-4e3d-a324-e7be83f05f5a.png)
