### ISSUE TITLE
Gandi provider in README but not in project

### ISSUE THREAD

**Issue by AlessandroPerucchi** [AnalogJ/lexicon#115]
I am using Gandi, and wanted to use lexicon to speak with it.
Unfortunately the provider is not available publicly. I have found it in the issues... but doesn't work correctly.
I would be nice to correct it and add it to the project!
Thank you in advance for your work :-)

**Comment by AlessandroPerucchi** [comment]
This is the error I get:
Namespace(action='create', auth_token=None, content='XYZ', delegated=None, domain='test.example.com', identifier=None, name='_acme-challenge.test.example.com.', priority=None, provider_name='gandi', ttl=None, type='TXT')
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 60, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 39, in execute
    return self.provider.create_record(self.options.get('type'), self.options.get('name'), self.options.get('content'))
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/gandi.py", line 88, in create_record
    'value': content})
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 581137: 'Error on object : OBJECT_DNS_RECORD (CAUSE_BADPARAMETER) [String does not match expected pattern]'>

**Comment by AlessandroPerucchi** [comment]
I have found the problem in fact, I was putting a . (dot) at the end of the NAME part to have a FQDN, and Gandi refuses that by sending that error.
I've corrected it, and now it works.

The problem now is either to include the gandi provider OR to remove it from the README.

**Comment by AnalogJ** [comment]
Hey @AlessandroPerucchi Yeah the Gandi provider was removed in a previous version because it was broken in a couple of different versions of python.

If you can fix it up and get it passing the tests, I'd be happy to merge a PR! :)

**Comment by AnalogJ** [comment]
re-added support for `gandi` in #130 (`v2.1.6`)
