### ISSUE TITLE
Lexicon aborts with an error at provider "euserv".

### ISSUE THREAD

**Issue by hubiuwe** [AnalogJ/lexicon#1299]
Lexicon aborts with an error at provider "euserv".
lexicon v3.11.3
Error message:
`Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/lexicon/cli.py", line 131, in main
    results = client.execute()
  File "/usr/local/lib/python3.8/dist-packages/lexicon/client.py", line 81, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python3.8/dist-packages/lexicon/providers/base.py", line 73, in authenticate
    self._authenticate()
  File "/usr/local/lib/python3.8/dist-packages/lexicon/providers/euserv.py", line 74, in _authenticate
    orders = auth_response["result"]["orders"]
KeyError: 'orders'
`

After a successful auth, the key "orders" is not transmitted  in login response.
This is also compliant with the [API Docs](https://support.euserv.com/api-doc/#api-Customer-login)
I don't know why it worked before.

Sorry for my bad english
thx Uwe

**Comment by bernhardfrenking** [comment]
Hello @hubiuwe,

if you want to query your orders 
use the following requests in its order:

1. "newSessionId" to get a Session Id
2. "login" with your Session Id
3. "showorders" with your Session Id

Then you should get your orders as a json.

Best regards
Bernhard
