### ISSUE TITLE
Fix logging TypeError (digitalocean.py)

### ISSUE THREAD

**Issue by david-rahrer** [AnalogJ/lexicon#132]
[This same issue](https://github.com/AnalogJ/lexicon/pull/128/commits/903af58378ab9942d817c57e0330b5f7ac26b4e9) exists in `lexicon/providers/digitalocean.py` line 111. The same edit is needed to fix it. 

The error generated is:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file digitalocean.py, line 111
```
That section is:
```
 Line 110: # is always True at this point, if a non 200 response is returned an error is raised.
 Line 111: logger.debug('delete_record: {0}', True)
 Line 112: return True
```

**Comment by AnalogJ** [comment]
damn. I wonder how many other places this has creeped in.
