### ISSUE TITLE
Cloudflare - 405 while deleting a TXT record (cloudflare.py#L172-L183)

### ISSUE THREAD

**Issue by aaccioly** [AnalogJ/lexicon#1721]
Hello, sorry for crossposting it here, but this is basically a duplicate of adferrand/dnsrobocert#1017. At the moment I'm not sure if this is an error on my part, a potential issue with @adferrand's implementation or with lexicon's cloudflare API itself. 

As per the title, I'm currently getting the following error (ZoneID masked):

```
dnsrobocert  | Hook '--manual-cleanup-hook' for satdomain.net reported error code 1
dnsrobocert  | Hook '--manual-cleanup-hook' for satdomain.net ran with error output:
dnsrobocert  |  Error while executing the `cleanup` hook:
dnsrobocert  |  405 Client Error: Method Not Allowed for url: https://api.cloudflare.com/client/v4/zones/eb111c0fc0000f000c0000ec0d000000/dns_records/TXT
dnsrobocert  |  Traceback (most recent call last):
dnsrobocert  |    File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 40, in main
dnsrobocert  |      globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
dnsrobocert  |    File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 123, in cleanup
dnsrobocert  |      txt_challenge(certificate, profile, token, domain, action="delete")
dnsrobocert  |    File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/challenge.py", line 57, in txt_challenge
dnsrobocert  |      operations.delete_record("TXT", challenge_name, token)
dnsrobocert  |    File "/usr/local/lib/python3.9/site-packages/lexicon/client.py", line 73, in delete_record
dnsrobocert  |      return self.provider.delete_record(identifier, rtype, name, content)
dnsrobocert  |    File "/usr/local/lib/python3.9/site-packages/lexicon/_private/providers/cloudflare.py", line 183, in delete_record
dnsrobocert  |      self._delete(f"/zones/{self.domain_id}/dns_records/{record_id}")
dnsrobocert  |    File "/usr/local/lib/python3.9/site-packages/lexicon/interfaces.py", line 187, in _delete
dnsrobocert  |      return self._request("DELETE", url, query_params=query_params)
dnsrobocert  |    File "/usr/local/lib/python3.9/site-packages/lexicon/_private/providers/cloudflare.py", line 210, in _request
dnsrobocert  |      response.raise_for_status()
dnsrobocert  |    File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
dnsrobocert  |      raise HTTPError(http_error_msg, response=self)
dnsrobocert  |  requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://api.cloudflare.com/client/v4/zones/eb111c0fc0000f000c0000ec0d000000/dns_records/TXT
``` 

The parameters passed to lexicon's client by DNSroboCert's [challenge.py#L57](https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/challenge.py#L57) looks fine to me.

More than that, by simulating what is happening at [cloudflare.py#L172-L183](https://github.com/AnalogJ/lexicon/blob/f8e461499389be3100b264b5b65942efbf9327bb/src/lexicon/_private/providers/cloudflare.py#L172-L183) manually with Cloudflare's API everything works as supposed.

```shell
❯ curl -s --request GET \
  --url "https://api.cloudflare.com/client/v4/zones/eb111c0fc0000f000c0000ec0d000000/dns_records?type=TXT&name=_acme-challenge.mydomain.net" \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
  | jq '.result[].id'
"bab02ba78f33352a034a98f7781534e0"
"c9716674986e3f7029f6b93a73f1a456"
❯ curl -s --request DELETE \
  --url "https://api.cloudflare.com/client/v4/zones/eb111c0fc0000f000c0000ec0d000000/dns_records/bab02ba78f33352a034a98f7781534e0" \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
{"result":{"id":"bab02ba78f33352a034a98f7781534e0"},"success":true,"errors":[],"messages":[]}%
❯ curl -s --request DELETE \
  --url "https://api.cloudflare.com/client/v4/zones/eb111c0fc0000f000c0000ec0d000000/dns_records/c9716674986e3f7029f6b93a73f1a456" \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
{"result":{"id":"c9716674986e3f7029f6b93a73f1a456"},"success":true,"errors":[],"messages":[]}%
```

Any ideas on where the issue may be?

**Comment by aaccioly** [comment]
I think that I have found the culprit and have a potential fix at the other repository (adferrand/dnsrobocert#1018), tentatively closing this
