### ISSUE TITLE
Partial credentials error for Route53

### ISSUE THREAD

**Issue by david-rahrer** [AnalogJ/lexicon#184]
I am trying to use route53 with lexicon and getssl. I have done this just fine with a number of other providers but this is driving me crazy. The API access information is store in env variables with this setup so here is what I am using. I've created a new IAM user with full permissions for route53 and added these credentials as below:

export LEXICON_PROVIDER="route53"
export LEXICON_ROUTE53_USERNAME="username"
export LEXICON_ROUTE53_KEY="Access key ID"
export LEXICON_ROUTE53_SECRET="Secret Key"

When I run it, I get the following:

```
Registering account
Verify each domain
Verifying mydomain.com
Arguments: Namespace(action='create', auth_access_key=None, auth_access_secret=None, auth_token=None, auth_username=None, content='ra4VRyWApFTUDi6_k2BDw7cd3o68-P2tt7BDEFUGugU', delegated=None, domain='mydomain.com', identifier=None, name='_acme-challenge.mydomain.com.', priority=None, provider_name='route53', ttl=None, type='TXT')
Loading variable profile from defaults.
Loading variable config_file from defaults.
Loading variable credentials_file from defaults.
Loading variable data_path from defaults.
Loading variable profile from defaults.
Loading variable region from defaults.
Loading variable profile from defaults.
Loading variable ca_bundle from defaults.
Loading variable profile from defaults.
Loading variable api_versions from defaults.
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==2.1.8', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 68, in main
    client = Client(parsed_args.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 34, in __init__
    self.provider = provider_class(self.options)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/route53.py", line 89, in __init__
    aws_secret_access_key=self.options.get('auth_access_secret', self.options.get('auth_token'))
  File "/usr/local/lib/python2.7/dist-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 848, in create_client
    aws_secret_access_key))
botocore.exceptions.PartialCredentialsError: Partial credentials found in explicit, missing: aws_secret_access_key
getssl: DNS_ADD_COMMAND failed for domain mydomain.com
```

It is my understanding that LEXICON_ROUTE53_SECRET is the variable name for aws_secret_access_key to use. I've triple checked the information and I can't get past this. Could anyone point me in the right direction? Thanks very much.

**Comment by david-rahrer** [comment]
After more trial and error and digging through some of the code, I struck on the right setup in case anyone else runs into this. This might have been better asked on the getssl page but there is some crossover so maybe this will help someone. 

```
export LEXICON_PROVIDER="route53"
export LEXICON_ROUTE53_USERNAME="AWS_ACCESS_KEY"
export LEXICON_ROUTE53_TOKEN="AWS_SECRET_ACCESS_KEY"
```
