### ISSUE TITLE
Debugging Cloudflare failure

### ISSUE THREAD

**Issue by ginkel** [AnalogJ/lexicon#186]
lexicon 2.1.24

I'm using lexicon as DNS provider for dehydrated. Unfortunately, for one of the challenges that dehydrated attempts to register through Cloudflare I am consistently getting a 400 HTTP error:

```
2018-03-14T19:42:06.906733698Z Processing hh.<domain>.net with alternative names: *.hh.<domain>.net 
2018-03-14T19:42:06.941869818Z  + Signing domains...
2018-03-14T19:42:06.942159973Z  + Generating private key...
2018-03-14T19:42:19.120036109Z  + Generating signing request...
2018-03-14T19:42:19.330905486Z  + Requesting new certificate order from CA...
2018-03-14T19:42:21.186401745Z  + Received 2 authorizations URLs from the CA
2018-03-14T19:42:21.775531640Z  + Handling authorization for hh.<domain>.net
2018-03-14T19:42:22.407199825Z  + Handling authorization for hh.<domain>.net
2018-03-14T19:42:22.493864477Z  + 2 pending challenge(s)
2018-03-14T19:42:22.493989008Z  + Deploying challenge tokens...
2018-03-14T19:42:22.508123404Z deploy_challenge called: hh.<domain>.net, GAdFi6UOGFp7bEKXvM1MqZ1F2O7ed0yItfVaPrcIRrM, mN99uipm4NDhSTmvl4tQiwXCmXqnMfDdmddCthqQu-U
2018-03-14T19:42:24.256119223Z Arguments: Namespace(action='create', auth_token=None, auth_username=None, content='mN99uipm4NDhSTmvl4tQiwXCmXqnMfDdmddCthqQu-U', delegated=None, domain='hh.<domain>.net', identifier=None, log_level='DEBUG', name='_acme-challenge.hh.<domain>.net.', priority=None, provider_name='cloudflare', ttl=None, type='TXT')
2018-03-14T19:42:24.299216992Z Starting new HTTPS connection (1): api.cloudflare.com
2018-03-14T19:42:25.556367127Z https://api.cloudflare.com:443 "GET /client/v4/zones?name=<domain>.net&status=active HTTP/1.1" 200 None
2018-03-14T19:42:25.596813444Z Starting new HTTPS connection (1): api.cloudflare.com
2018-03-14T19:42:26.593873112Z https://api.cloudflare.com:443 "POST /client/v4/zones/<id>/dns_records HTTP/1.1" 400 None
2018-03-14T19:42:26.617382174Z Traceback (most recent call last):
2018-03-14T19:42:26.617868632Z   File "/usr/local/bin/lexicon", line 11, in <module>
2018-03-14T19:42:26.621587217Z     load_entry_point('dns-lexicon==2.1.24', 'console_scripts', 'lexicon')()
2018-03-14T19:42:26.621751019Z   File "/usr/local/lib/python3.5/dist-packages/lexicon/__main__.py", line 72, in main
2018-03-14T19:42:26.622473517Z     client.execute()
2018-03-14T19:42:26.622588778Z   File "/usr/local/lib/python3.5/dist-packages/lexicon/client.py", line 41, in execute
2018-03-14T19:42:26.623328828Z     return self.provider.create_record(self.options.get('type'), self.options.get('name'), self.options.get('content'))
2018-03-14T19:42:26.623446640Z   File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/cloudflare.py", line 45, in create_record
2018-03-14T19:42:26.624159139Z     payload = self._post('/zones/{0}/dns_records'.format(self.domain_id), data)
2018-03-14T19:42:26.624269034Z   File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/base.py", line 76, in _post
2018-03-14T19:42:26.625105334Z     return self._request('POST', url, data=data, query_params=query_params)
2018-03-14T19:42:26.625217782Z   File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/cloudflare.py", line 125, in _request
2018-03-14T19:42:26.626222259Z     r.raise_for_status()  # if the request fails for any reason, throw an error.
2018-03-14T19:42:26.626345384Z   File "/usr/lib/python3/dist-packages/requests/models.py", line 893, in raise_for_status
2018-03-14T19:42:26.630342302Z     raise HTTPError(http_error_msg, response=self)
2018-03-14T19:42:26.630504125Z requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones/73b5d5210fc685cac30af7b41dd91ba4/dns_records

```

Any ideas how to debug this? I'd assume that Cloudflare returns an error in the HTTP response body, but it is currently swallowed...

**Comment by alexzorin** [comment]
If you are getting desperate, you could try modify `/usr/local/lib/python3.5/dist-packages/lexicon/providers/cloudflare.py`

Adding

```py
print(r.text)
```

before this line:

https://github.com/AnalogJ/lexicon/blob/a1f5fcdb210db2f29ca3e59e01afd5862744ebde/lexicon/providers/cloudflare.py#L125

**Comment by AnalogJ** [comment]
Hey @ginkel  are you still having this issue?
Sorry I've been busy working on a different high-priority lexicon issue, and kinda let these other issues fall flat.

**Comment by AnalogJ** [comment]
Hey @ginkel is this still a problem for you?

**Comment by AnalogJ** [comment]
Closing.

**Comment by ginkel** [comment]
Apologies for not responding earlier... I eventually tracked down the error to the challenge already being present in Cloudflare's DNS (due to a failed prior attempt). Maybe it would be a good idea to make sure the API invocations are idempotent.

**Comment by AnalogJ** [comment]
Oh no problem. 

Thats actually one of the big changes we added to the test suite recently. Newer versions of lexicon should be idempotent and support record sets correctly.
