### ISSUE TITLE
[easyname] provider broken (security code/2FA, REST API)

### ISSUE THREAD

**Issue by pannal** [AnalogJ/lexicon#1925]
```Hook '--manual-auth-hook' for asdf.domain ran with error output:
 Traceback (most recent call last):
   File "/usr/local/bin/lexicon", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.10/dist-packages/lexicon/cli.py", line 131, in main
     results = client.execute()
   File "/usr/local/lib/python3.10/dist-packages/lexicon/client.py", line 81, in execute
     self.provider.authenticate()
   File "/usr/local/lib/python3.10/dist-packages/lexicon/providers/base.py", line 73, in authenticate
     self._authenticate()
   File "/usr/local/lib/python3.10/dist-packages/lexicon/providers/easyname.py", line 91, in _authenticate
     self._login(csrf_token)
   File "/usr/local/lib/python3.10/dist-packages/lexicon/providers/easyname.py", line 83, in _login
     assert json_response["redirectUrl"] == self.URLS["dashboard"], (
 KeyError: 'redirectUrl'
```
dns-lexicon==3.11.7

**Comment by elpollodiablo** [comment]
> OK, this seems to be due to an easyname change: They now either require 2FA or a security code sent via email when logging in. I think the provider needs to be changed to use their REST API instead of crawling.
> 
> https://api-docs.easyname.com/

The rest API does not support changing dns records. I'm considering switching to a completely different domain provider due to this :(

**Comment by adferrand** [comment]
Do have have a solution using the APIs now ?
