### ISSUE TITLE
NameError: global name 'namecheap' is not defined

### ISSUE THREAD

**Issue by kaysond** [AnalogJ/lexicon#235]
I'm running the following command on Ubuntu 17.10: ` sudo -H lexicon namecheap list google.com CNAME --auth-sandbox` (I realize its bogus and won't work, but my actual command fails too with the same error.)

and I get the following error:

```
Arguments: Namespace(action='list', auth_client_ip='127.0.0.1', auth_sandbox=True, auth_token=None, auth_username=None, content=None, delegated=None, domain='google.com', identifier=None, log_level='DEBUG', name=None, priority=None, provider_name='namecheap', ttl=None, type='CNAME')
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 71, in main
    client = Client(parsed_args.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 35, in __init__
    self.provider = provider_class(self.options)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/namecheap.py", line 66, in __init__
    self.client = namecheap.Api(
NameError: global name 'namecheap' is not defined
```

I'm using Python 2.7.14. What am I doing wrong?

**Comment by CapsuleCD** [comment]
Looks like you need to run pip install dns-lexicon[namecheap] to install
the namecheap dependencies

**Comment by kaysond** [comment]
That was it. Thanks!
