### ISSUE TITLE
Softlayer DNS Forward Zones issue

### ISSUE THREAD

**Issue by ckuai** [AnalogJ/lexicon#255]
Hello,

I am not sure if this is a Bug or not supported Feature.

I have a issue to get softlayer works with DNS Forward Zone and with Certbot manual it works with some hack. For example
1. create a DNA Forward Zone as "sub.example.com" on Softlayer DNS Forward Zone
2. then in that zone I add addition A records for my sub domains under test.example.com such as 
env1.test.sub.example.com 
env1.api1.test.sub.example.com 
env1.api2.test.sub.example.com 
env2.test.sub.example.com 
env2.api1.test.sub.example.com 
env2.api2.test.sub.example.com
.....
3. with certbot
certbot-auto certonly --manual \
-d test.sub.example.com  \
-d *.test.sub.example.com  \
-d *.api1.test.sub.example.com  \
-d *.api2.test.sub.example.com  \
--preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory

Certbot would ask me to add txt records for example, _acme-challenge.test.sub.example.com.

Here is the little hack comes in, I will have to add TXT record to "sub.example.com" as "_acme-challenge.test" and strip "sub.example.com" from what instructed by Certbot for it to work. Otherwise I will get challenge error.

But with Lexicon. I got following error. for "No Domain Found"

```
lexicon softlayer --auth-api=userAToken --auth-username=userA "create" "test.spop-sl.com" TXT --name "_acme-challenge.test" --content "TXT_TEXT"

Arguments: Namespace(action='create', auth_api_key='userAToken', auth_username='userA', content='TXT_TEXT', delegated=None, domain='test.spop-sl.com', identifier=None, log_level='DEBUG', name='_acme-challenge.test', priority=None, provider_name='softlayer', ttl=None, type='TXT')
Starting new HTTPS connection (1): api.softlayer.com:443
https://api.softlayer.com:443 "POST /xmlrpc/v3.1/SoftLayer_Account HTTP/1.1" 200 110
Traceback (most recent call last):
  File "/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==2.4.4', 'console_scripts', 'lexicon')()
  File "/usr/lib/python2.7/site-packages/lexicon/__main__.py", line 72, in main
    client.execute()
  File "/usr/lib/python2.7/site-packages/lexicon/client.py", line 38, in execute
    self.provider.authenticate()
  File "/usr/lib/python2.7/site-packages/lexicon/providers/softlayer.py", line 45, in authenticate
    raise Exception('No domain found')
Exception: No domain found
```

**Comment by ckuai** [comment]
never mind, it was my mistake. I didn't setup my DNS record correctly.
