### ISSUE TITLE
Need help with Hetzner

### ISSUE THREAD

**Issue by Scifire** [AnalogJ/lexicon#347]
I´m trying to setup lexicon with hetzner but i don´t get it to work:

System Ubutnu 16.04
```
# pip freeze
acme==0.28.0
asn1crypto==0.22.0
beautifulsoup4==4.7.1
certbot==0.28.0
certbot-apache==0.28.0
certifi==2017.4.17
chardet==3.0.4
ConfigArgParse==0.11.0
configobj==5.0.6
cryptography==1.9
dns-lexicon==3.0.8
dnspython==1.16.0
fail2ban==0.9.3
funcsigs==0.4
future==0.15.2
idna==2.5
josepy==1.1.0
mock==1.3.0
ndg-httpsclient==0.4.2
parsedatetime==2.4
pbr==1.8.0
pyasn1==0.1.9
PyICU==1.9.2
pyinotify==0.9.6
pyOpenSSL==17.3.0
pyRFC3339==1.0
python-apt==1.1.0b1+ubuntu0.16.4.2
python-augeas==0.5.0
python-systemd==231
pytz==2014.10
PyYAML==3.13
requests==2.18.1
requests-file==1.4.3
requests-toolbelt==0.8.0
six==1.11.0
soupsieve==1.7.3
tldextract==2.2.0
urllib3==1.21.1
zope.component==4.3.0
zope.event==4.2.0
zope.hookable==4.0.4
zope.interface==4.3.2
```
tried it with this syntax (not sure if it´s correct):
`lexicon hetzner list mydomain.de TXT --auth-account robot --auth-username mymail@gmail.com --auth-password 'mypassword'`

then i got: 
```
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/usr/local/lib/python3.5/dist-packages/lexicon/client.py", line 64, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/hetzner.py", line 168, in authenticate
    with self._session(self.domain, get_zone=False):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/hetzner.py", line 592, in _session
    qdomain, nameservers, cname = Provider._get_dns_cname((name if name else domain+'.'), link)
  File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/hetzner.py", line 465, in _get_dns_cname
    domain = dns.resolver.zone_for_name(name, resolver=resolver).to_text(True)
  File "/usr/local/lib/python3.5/dist-packages/dns/resolver.py", line 1132, in zone_for_name
    answer = resolver.query(name, dns.rdatatype.SOA, rdclass, tcp)
  File "/usr/local/lib/python3.5/dist-packages/dns/resolver.py", line 900, in query
    timeout = self._compute_timeout(start, lifetime)
  File "/usr/local/lib/python3.5/dist-packages/dns/resolver.py", line 799, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 1.000643253326416 seconds
```
Can anyone tell me what i´m doing wrong/wheres the mistake?

**Comment by Scifire** [comment]
@adferrand thanks for your fast answer.
I use my own local dns resolver (unbound) which is really not slow 
```
dig scifire.de | grep "Query time"
;; Query time: 0 msec
```
And names which could be not local resolved will be resolved by 8.8.8.8

But could that local unbound the problem?

**Comment by rembik** [comment]
Indeed, this is strange behavior. I guess the required ports in your environment are open and firewalls allow you to request the Hetzner DNS who should response to the DNS query?

Could you please provide an anonymized log with:
`lexicon hetzner list mydomain.de TXT --auth-account robot --auth-username mymail@gmail.com --auth-password 'mypassword' --log_level DEBUG`

**Comment by AnalogJ** [comment]
Hey @Scifire 
Have you gotten this working?

**Comment by Scifire** [comment]
@AnalogJ  currently i didn't come to it... After i'm back at home will try it and report the result here

**Comment by Scifire** [comment]
@rembik here's the log:

```
root@scifire ~ # lexicon hetzner list scifire.de TXT --auth-account robot --auth-username mymail@gmail.com --auth-password 'mypass' --log_level DEBUG
Arguments: Namespace(action='list', auth_account='robot', auth_password='mypass', auth_username='mymail@gmail.com', content=None, delegated=None, domain='scifire.de', identifier=None, latency=30, linked='yes', log_level='DEBUG', name=None, output='TABLE', priority=None, propagated='yes', provider_name='hetzner', ttl=None, type='TXT')
Hetzner => Disable CNAME lookup (see --linked parameter)
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/usr/local/lib/python3.5/dist-packages/lexicon/client.py", line 64, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/hetzner.py", line 168, in authenticate
    with self._session(self.domain, get_zone=False):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/hetzner.py", line 592, in _session
    qdomain, nameservers, cname = Provider._get_dns_cname((name if name else domain+'.'), link)
  File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/hetzner.py", line 465, in _get_dns_cname
    domain = dns.resolver.zone_for_name(name, resolver=resolver).to_text(True)
  File "/usr/local/lib/python3.5/dist-packages/dns/resolver.py", line 1132, in zone_for_name
    answer = resolver.query(name, dns.rdatatype.SOA, rdclass, tcp)
  File "/usr/local/lib/python3.5/dist-packages/dns/resolver.py", line 900, in query
    timeout = self._compute_timeout(start, lifetime)
  File "/usr/local/lib/python3.5/dist-packages/dns/resolver.py", line 799, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 1.0010573863983154 seconds

```

**Comment by rembik** [comment]
„Also check if your unbound DNS is configured as nameserver in /etc/resolv.conf, because those will be used as default for DNS resolution.“

**Comment by Scifire** [comment]
Looks like it is now working. 
Maybe my unbound wasn´t working properly cause this day i found an error which i fixed (can´t remember it was there the last time...).

@rembik and @adferrand thanks a lot for your help 👍
