### ISSUE TITLE
Digitalocean Provider spits out invalid json

### ISSUE THREAD

**Issue by napcae** [AnalogJ/lexicon#35]
```
[  
   {  
      'content':u'"v=DKIM1; k=rsa; p=MIGfMA0GC[...redacted...]GUrwFVgQIDAQAB"',
      'id':1256011,
      'type':u'TXT',
      'name':'mesmtp._domainkey.ctnguyen.net',
      'ttl':''
   },
   {  
      'content':      u'"v=spf1 include:spf.messagingengine.com -all"',
      'id':2349116,
      'type':u'TXT',
      'name':'@.ctnguyen.net',
      'ttl':''
   }
]
```

The issued command is ```lexicon digitalocean list ctnguyen.net --auth-token $LEXICON_DIGITALOCEAN_TOKEN TXT```

Look after the `content`-pair and `type`-pair. There are _u_'s after the colon. I don't were there are coming from. 
I discovered this, when I tried to setup letsencrypt.sh with the provided example hook. 
The `clean_challenge` returns an empty list(maybe because the json is invalid).

**Comment by napcae** [comment]
What exactly do you need me to do? Regarding the test suites?

```bash
# lexicon digitalocean delete ctnguyen.net --name '_acme.challenge.ctnguyen.net' --auth-token $LEXICON_DIGITALOCEAN_TOKEN TXT
Namespace(action='delete', auth_token='32dc[...redacted...]d559348', content=None, domain='ctnguy
en.net', identifier=None, name='_acme.challenge.ctnguyen.net', priority=None, provider_name='digitalocean', ttl=None, type='TXT')
list_records: []
[]
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==1.1.2', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 51, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 37, in execute
    return self.provider.delete_record(self.options.get('identifier'), self.options.get('type'), self.options.get('name'), self.options.get('content'))
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/digitalocean.py", line 88, in delete_record
    raise StandardError('Record identifier could not be found.')
StandardError: Record identifier could not be found.
```
I meant that list, see line 5?

Regarding the --auth-token:
````
root at duplo in /usr/local/sbin/letsencrypt.sh on master*
# lexicon digitalocean list _acme-challenge.ctnguyen.net TXT
Namespace(action='list', auth_token=None, content=None, domain='_acme-challenge.ctnguyen.net', identifier=None, name=None, priority=None, provider_name='digitalocean', ttl=None, type='TXT')
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==1.1.2', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 51, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 25, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/digitalocean.py", line 17, in authenticate
    payload = self._get('/domains/{0}'.format(self.options['domain']))
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/base.py", line 35, in _get
    return self._request('GET', url, query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/digitalocean.py", line 111, in _request
    r.raise_for_status()  # if the request fails for any reason, throw an error.
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.digitalocean.com/v2/domains/ctnguyen.net
root at duplo in /usr/local/sbin/letsencrypt.sh on master*
# echo $LEXICON_DIGITALOCEAN_TOKEN
32dcbe5[...redacted...]559348
```
Somehow the env variable isn't picked up. Maybe I'm overlooking something obvious?

**Comment by AnalogJ** [comment]
That first command looks incorrect, lexicon is failing because its trying to delete a record that doesn't exist. I think it should be `_acme-challenge.ctnguyen.net` instead of `_acme.challenge.ctnguyen.net`
You said it's failing when using the provided [letsencrypt.sh hook](https://github.com/AnalogJ/lexicon/tree/master/examples). Can you paste the output from it?

you might want to try exporting the `token` environmental variable.

    export LEXICON_DIGITALOCEAN_TOKEN=sdfsdf

**Comment by napcae** [comment]
You are right, that doesn't change the fact, that the call from letsencrypt.sh hook is failing though: 

```
root at duplo in /usr/local/sbin/letsencrypt.sh on master*
# ./letsencrypt.sh -c -k ./letsencrypt.default.sh
# INFO: Using main config file /usr/local/sbin/letsencrypt.sh/config.sh
Processing ctnguyen.net with alternative names: www.ctnguyen.net
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for ctnguyen.net...
 + Requesting challenge for www.ctnguyen.net...
deploy_challenge called: ctnguyen.net, B5zJb3tmWo0Ip-GP_tzJEN29ZZcTcuRCRbf-PVbMN10, iTufss1HCt-OVeqg0ttlGOrbidx58vixEZ3Lzufatbs
Namespace(action='create', auth_token='32d[......]348', content='iTufss1HCt-OVeqg0ttlGOrbidx58vixEZ3Lzufatbs', domain='ctnguyen.net', identifier=None, name='_acme-challenge.ctnguyen.net.', priority=None, provider_name='digitalocean', ttl=None, type='TXT')
create_record: True
 + Responding to challenge for ctnguyen.net...
clean_challenge called: ctnguyen.net, B5zJb3tmWo0Ip-GP_tzJEN29ZZcTcuRCRbf-PVbMN10, iTufss1HCt-OVeqg0ttlGOrbidx58vixEZ3Lzufatbs
Namespace(action='delete', auth_token='32d[......]348', content='iTufss1HCt-OVeqg0ttlGOrbidx58vixEZ3Lzufatbs', domain='ctnguyen.net', identifier=None, name='_acme-challenge.ctnguyen.net.', priority=None, provider_name='digitalocean', ttl=None, type='TXT')
list_records: []
[]
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==1.1.2', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 51, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 37, in execute
    return self.provider.delete_record(self.options.get('identifier'), self.options.get('type'), self.options.get('name'), self.options.get('content'))
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/digitalocean.py", line 88, in delete_record
    raise StandardError('Record identifier could not be found.')
StandardError: Record identifier could not be found.
```

While you can see, that the record clearly exists:
````
napcae at earth in ~/www/files
$ dig _acme-challenge.ctnguyen.net txt

; <<>> DiG 9.10.2-P2 <<>> _acme-challenge.ctnguyen.net txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62198
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 3, ADDITIONAL: 7

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_acme-challenge.ctnguyen.net.  IN      TXT

;; ANSWER SECTION:
_acme-challenge.ctnguyen.net. 1800 IN   TXT     "iTufss1HCt-OVeqg0ttlGOrbidx58vixEZ3Lzufatbs"

;; AUTHORITY SECTION:
ctnguyen.net.           172799  IN      NS      ns3.digitalocean.com.
ctnguyen.net.           172799  IN      NS      ns2.digitalocean.com.
ctnguyen.net.           172799  IN      NS      ns1.digitalocean.com.

;; ADDITIONAL SECTION:
ns1.digitalocean.com.   407     IN      A       173.245.58.51
ns1.digitalocean.com.   141440  IN      AAAA    2400:cb00:2049:1::adf5:3a33
ns2.digitalocean.com.   407     IN      A       173.245.59.41
ns2.digitalocean.com.   141440  IN      AAAA    2400:cb00:2049:1::adf5:3b29
ns3.digitalocean.com.   171709  IN      A       198.41.222.173
ns3.digitalocean.com.   141440  IN      AAAA    2400:cb00:2049:1::c629:dead

;; Query time: 369 msec
;; SERVER: 213.186.33.99#53(213.186.33.99)
;; WHEN: Thu Apr 21 22:39:38 CEST 2016
;; MSG SIZE  rcvd: 315
```

**Comment by AnalogJ** [comment]
hmm. Are you still seeing this issue? I tried to replicate this over the weekend, but I didn't get any errors.

**Comment by napcae** [comment]
Yes, still the same error..:/

**Comment by jokester** [comment]
@napcae I found an issue in #40 that may be related to your problem.

Would you mind try the code in [this branch](https://github.com/jokester/lexicon/tree/digitalocean-ignore-content-case)? I had identical error as [yours](https://github.com/AnalogJ/lexicon/issues/35#issuecomment-213105616) and this code did help on my end.

**Comment by napcae** [comment]
Ah, sorry for the late reply. I did try it, but forgot to answer. Anyway - same error. So no fix yet for me :(

**Comment by AnalogJ** [comment]
Hey @napcae can you try using the latest version of lexicon? v1.1.9 and if you're still running into errors can you include the output of `pip list`? Thanks!

**Comment by mrwacky42** [comment]
Perhaps OP has the same problem as me: Lexicon doesn't deal with paginated results from DigitalOcean. The challenge TXT record is in the second page of results for me.

I found a nice solution here: https://github.com/Wiredcraft/dopy/pull/31/files

**Comment by napcae** [comment]
Hey @AnalogJ & @mrwacky42 
That could be the problem. Although I think I also tried it with a domain which had a smaller zone file and still had the same problem. I'm not using lexicon anymore.

**Comment by AnalogJ** [comment]
@mrwacky42 
Sorry I just noticed your response. Yeah that sounds like it could definitely cause some issues. Would you be willing to open a PR with the pagination fix on the DO provider?
