### ISSUE TITLE
Error in hetzner-Provider while reading DNS-Zone

### ISSUE THREAD

**Issue by migmedia** [AnalogJ/lexicon#376]
I get a error while reading a zone-file from hetzner. 

What went wrong? Does it work at someone else?

`lexicon hetzner --log_level DEBUG list example.com TXT`

```
Starting new HTTPS connection (1): accounts.hetzner.com
https://accounts.hetzner.com:443 "GET /login HTTP/1.1" 200 2995
https://accounts.hetzner.com:443 "POST /login_check HTTP/1.1" 302 197                                                                                 
https://accounts.hetzner.com:443 "GET / HTTP/1.1" 200 3040
Hetzner => Authenticate session with robot account 'test@example.com'
Starting new HTTPS connection (1): robot.your-server.de                                           
https://robot.your-server.de:443 "GET /dns/index/page/1 HTTP/1.1" 302 None
https://accounts.hetzner.com:443 "GET /oauth/authorize?client_id=robot_000&redirect_uri=https%3A%2F%2Frobot.your-server.de%2Flogin%2Fcheck&response_ty
pe=code&scope=openid&state=039b55fcb305c40a29ade2665f872688 HTTP/1.1" 200 3170                                                                       
https://robot.your-server.de:443 "GET /login/logout/r/true HTTP/1.1" 302 None                                                                        
https://accounts.hetzner.com:443 "GET /logout?post_logout_redirect_uri=https://robot.your-server.de/ HTTP/1.1" 200 3075                              
Hetzner => Exit session                  
Traceback (most recent call last):                     
  File "/usr/lib/python-exec/python3.6/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==3.1.5', 'console_scripts', 'lexicon')()
  File "/usr/lib64/python3.6/site-packages/lexicon/cli.py", line 117, in main                                                                        
    results = client.execute()                                           
  File "/usr/lib64/python3.6/site-packages/lexicon/client.py", line 64, in execute                                                                   
    self.provider.authenticate()                                          
  File "/usr/lib64/python3.6/site-packages/lexicon/providers/base.py", line 69, in authenticate                                                       
    return self._authenticate()                                               
  File "/usr/lib64/python3.6/site-packages/lexicon/providers/hetzner.py", line 171, in _authenticate                                                 
    with self._session(self.domain, get_zone=False):                                                                   
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)         
  File "/usr/lib64/python3.6/site-packages/lexicon/providers/hetzner.py", line 606, in _session                                                      
    raise exc                                                             
  File "/usr/lib64/python3.6/site-packages/lexicon/providers/hetzner.py", line 599, in _session                                                      
    qdomain_id = self._get_domain_id(qdomain)                                                                                                         
  File "/usr/lib64/python3.6/site-packages/lexicon/providers/hetzner.py", line 665, in _get_domain_id                                                
    for domain_tag in domain_tags:                      
TypeError: 'NoneType' object is not iterable                                                                                                         
```

**Comment by rembik** [comment]
I suggest you manage the domain with the Hetzner domain registration robot and you already created the [Hetzner robot DNS entry](https://wiki.hetzner.de/index.php/DNS_Robot/en)?

**Comment by migmedia** [comment]
The dns is fully complete and functional since 10 years...

Maybe it confilcts with the activated 2FA: 

>  **Are there any important limitations or other things I should know about 2FA?**
> After you activate 2FA, you will no longer be able to log in with the current user name and password:
>   * Robot email interface: Please use the GPG signature in this situation.
>   * Robot Mobile: Please use the webservice user in this case.
>   * Robot Webservice: Please use the webservice user.

**Comment by rembik** [comment]
2FA auth is not supported for the implemented Hetzner DNS API. So, this could be the reason for failing.

**Comment by migmedia** [comment]
Yes, thank you. After switching of 2FA it works as expercted.
