### ISSUE TITLE
Hetzner => ID for domain org does not exists

### ISSUE THREAD

**Issue by sceptiq** [AnalogJ/lexicon#400]
Hey,

 I have several domains managed by hetzner. I m able to query every one successfully except the one that is a .org:

```
Hetzner => ID for domain org does not exists
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==3.2.1', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python3.4/dist-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/usr/local/lib/python3.4/dist-packages/lexicon/client.py", line 71, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python3.4/dist-packages/lexicon/providers/base.py", line 69, in authenticate
    return self._authenticate()
  File "/usr/local/lib/python3.4/dist-packages/lexicon/providers/hetzner.py", line 171, in _authenticate
    with self._session(self.domain, get_zone=False):
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/lexicon/providers/hetzner.py", line 606, in _session
    raise exc
  File "/usr/local/lib/python3.4/dist-packages/lexicon/providers/hetzner.py", line 599, in _session
    qdomain_id = self._get_domain_id(qdomain)
  File "/usr/local/lib/python3.4/dist-packages/lexicon/providers/hetzner.py", line 675, in _get_domain_id
    raise AssertionError
AssertionError
```

any ideas ? :) 

EDIT: I have only one .org ...

**Comment by sceptiq** [comment]
I think i figured it out... there was something wrong mit my dns resolution.

sry ..
