### ISSUE TITLE
Provider Hetzner not working 

### ISSUE THREAD

**Issue by bottee** [AnalogJ/lexicon#441]
Hello, 
I'm trying to get lexicon with Hetzner working:

```
export LEXICON_HETZNER_AUTH_ACCOUNT='konsoleh'
export LEXICON_HETZNER_AUTH_USERNAME='my_username'
export LEXICON_HETZNER_AUTH_PASSWORD='my_password'
lexicon hetzner list my_domain.de TXT
```
but I get the following errors:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dns/resolver.py", line 1139, in zone_for_name
    name = name.parent()
  File "/usr/local/lib/python3.6/dist-packages/dns/name.py", line 789, in parent
    raise NoParent
dns.name.NoParent: An attempt was made to get the parent of the root name
    or the empty name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/usr/local/lib/python3.6/dist-packages/lexicon/client.py", line 71, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python3.6/dist-packages/lexicon/providers/base.py", line 69, in authenticate
    return self._authenticate()
  File "/usr/local/lib/python3.6/dist-packages/lexicon/providers/hetzner.py", line 171, in _authenticate
    with self._session(self.domain, get_zone=False):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/lexicon/providers/hetzner.py", line 594, in _session
    (name if name else domain + '.'), link)
  File "/usr/local/lib/python3.6/dist-packages/lexicon/providers/hetzner.py", line 466, in _get_dns_cname
    domain = dns.resolver.zone_for_name(name, resolver=resolver).to_text(True)
  File "/usr/local/lib/python3.6/dist-packages/dns/resolver.py", line 1141, in zone_for_name
    raise NoRootSOA
dns.resolver.NoRootSOA: There is no SOA RR at the DNS root name. This should never happen!
```
What is the problem? I'm happy for any hints!

**Comment by adferrand** [comment]
Well, there is something wrong with your DNS zone. Are you sure it exists, and you did not make a typo? 

Lexicon complains about the absence of `SOA`. This is the SOA record, https://en.m.wikipedia.org/wiki/SOA_record, which is basically the mandatory entry to define a zone. Without it almost nothing in the DNS protocol can work.

**Comment by rembik** [comment]
Could be closed, because it is no lexicon issue.

**Comment by bottee** [comment]
Sorry for my late response. I'm sure it's not a typo as I tried it very often and at least I verified that the authentication worked.
Maybe It is because I only have a simple Webhosting account?
Anyway, meanwhile I changed to a different provider and it worked without problems.
Sorry for the inconvenience and thank you for your great work!
