### ISSUE TITLE
Environment variables AUTH Transip

### ISSUE THREAD

**Issue by Rayzilt** [AnalogJ/lexicon#472]
When using the environment variables to authenticate to Transip it seems that Lexicon doesn't use them.

Tested with our without the `_AUTH_` added to the variable name.

Using `--auth-username` and `--auth-api-key` does work.

```
(lexicon) root@server:/opt/lexicon/bin# export LEXICON_TRANSIP_AUTH_USERNAME="user"
(lexicon) root@server:/opt/lexicon/bin# export LEXICON_TRANSIP_AUTH_TOKEN="token"
(lexicon) root@server:/opt/lexicon/bin# ./lexicon transip --log_level DEBUG list example.com TXT
Arguments: Namespace(action='list', auth_api_key=None, auth_username=None, config_dir='/opt/lexicon/bin', content=None, delegated=None, domain='example.com', identifier=None, log_level='DEBUG', name=None, output='TABLE', priority=None, provider_name='transip', ttl=None, type='TXT')
Traceback (most recent call last):
  File "./lexicon", line 10, in <module>
    sys.exit(main())
  File "/opt/lexicon/lib/python3.7/site-packages/lexicon/cli.py", line 115, in main
    client = Client(config)
  File "/opt/lexicon/lib/python3.7/site-packages/lexicon/client.py", line 67, in __init__
    self.provider = provider_class(self.config)
  File "/opt/lexicon/lib/python3.7/site-packages/lexicon/providers/transip.py", line 52, in __init__
    raise Exception("No username and/or keyfile was specified")
Exception: No username and/or keyfile was specified
(lexicon) root@server:/opt/lexicon/bin#
```

```
(lexicon) root@server:/opt/lexicon/bin# ./lexicon --version
lexicon 3.3.12
(lexicon) root@server:/opt/lexicon/bin#
```

```
(lexicon) root@server:/opt/lexicon/bin# pip list
Package       Version
------------- ----------
certifi       2019.11.28
cffi          1.13.2
chardet       3.0.4
cryptography  2.8
dns-lexicon   3.3.12
future        0.18.2
idna          2.8
pip           18.1
pkg-resources 0.0.0
pycparser     2.19
pyOpenSSL     19.1.0
PyYAML        5.2
requests      2.22.0
requests-file 1.4.3
setuptools    40.8.0
six           1.13.0
suds-jurko    0.6
tldextract    2.2.2
transip       2.0.0
urllib3       1.25.7
wheel         0.33.6
(lexicon) root@server:/opt/lexicon/bin#
```

**Comment by Rayzilt** [comment]
I have to use variable LEXICON_TRANSIP_AUTH_API_KEY instead of  LEXICON_TRANSIP_AUTH_TOKEN
