### ISSUE TITLE
Tenant_id assert error running Lexicon DNS with Azure as provider

### ISSUE THREAD

**Issue by compusaurusrex** [AnalogJ/lexicon#488]
Hello
I set the env variables for Azure as follows (replaced values with x's):
AUTH_CLIENT_ID='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
AUTH_CLIENT_SECRET='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
AUTH_TENANT_ID='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
AUTH_SUBSCRIPTION_ID='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
RESOURCE_GROUP='ilumrg'

When I run lexicon I get this:

$ lexicon azure list ilumhs.com A
Traceback (most recent call last):
  File "/usr/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==3.3.18', 'console_scripts', 'lexicon')()
  File "/usr/lib/python2.7/site-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/usr/lib/python2.7/site-packages/lexicon/client.py", line 77, in execute
    self.provider.authenticate()
  File "/usr/lib/python2.7/site-packages/lexicon/providers/base.py", line 69, in authenticate
    return self._authenticate()
  File "/usr/lib/python2.7/site-packages/lexicon/providers/azure.py", line 210, in _authenticate
    assert tenant_id
AssertionError

Any suggestions or guidance would be appreciated!

**Comment by adferrand** [comment]
All environment variables need to be prefixed with `LEXICON_[PROVIDER_NAME]_`.

So for your situation, for instance `AUTH_CLIENT_ID` becomes `LEXICON_AZURE_AUTH_CLIENT_ID`.
