### ISSUE TITLE
Provider hetzner_konsoleh currently broken

### ISSUE THREAD

**Issue by hetzner** [AnalogJ/lexicon#493]
Most probably due changes in GUI the provider is currently broken:

```
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==3.3.19', 'console_scripts',
'lexicon')()
  File "/usr/local/lib/python3.6/site-packages/lexicon/cli.py", line 117,
in main
    results = client.execute()
  File "/usr/local/lib/python3.6/site-packages/lexicon/client.py", line
87, in execute
    return self.provider.list_records(record_type, name, content)
  File "/usr/local/lib/python3.6/site-packages/lexicon/providers/base.py",
line 94, in list_records
    return self._list_records(rtype=rtype, name=name, content=content)
  File
"/usr/local/lib/python3.6/site-packages/lexicon/providers/hetzner.py",
line 212, in _list_records
    with self._session(self.domain, self.domain_id) as ddata:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File
"/usr/local/lib/python3.6/site-packages/lexicon/providers/hetzner.py",
line 606, in _session
    raise exc
  File
"/usr/local/lib/python3.6/site-packages/lexicon/providers/hetzner.py",
line 603, in _session
    zone = self._get_zone(qdomain, qdomain_id)
  File
"/usr/local/lib/python3.6/site-packages/lexicon/providers/hetzner.py",
line 691, in _get_zone
    zone_file = Provider._filter_dom(dom,
zone_file_filter).renderContents().decode('UTF-8')
AttributeError: 'NoneType' object has no attribute 'renderContents'
```

The changed form elements in this form are:

new_records (contains the records beside from $TTL, NS and SOA)
ttl (zone ttl)

It should quite easy to fix.

**Comment by l0rn** [comment]
I take an attempt in fixing that - but does not seem to be trivial. As lexicon also supports setting new records the provider would need to route modifications to the correct inputs.

I think web scraping is highy instable and changes to this form might be subject to further changes in the future. I wouldn't want to invest time in this and my vote clearly goes to purge this from the codebase

**Comment by adferrand** [comment]
We can close this issue, since we removed the old hetzner provider.
