### ISSUE TITLE
`godaddy` provider fails under v3.3.24 given FDQN

### ISSUE THREAD

**Issue by eengstrom** [AnalogJ/lexicon#518]
Upon upgrading from 3.3.23 to .24, the `godaddy` provider fails when given a FQDN including a full stop.  e.g. `foo.example.com.` (note trailing period).  E.g.:

```
odin $ lexicon --version
lexicon 3.3.24

odin $ lexicon godaddy create example.com TXT --name=foo.example.com. --content=bar.example.com
Traceback [elided...]
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/example.com/records/CNAME/foo.example.com.

odin $ pip3 install dns-lexicon==3.3.23
[elided...]
Successfully installed dns-lexicon-3.3.23

odin $ lexicon --version
lexicon 3.3.23

odin $ lexicon godaddy create example.com TXT --name=foo.example.com. --content=bar.example.com
RESULT
------
True
```

Looks like there have been a lot of changes recently, so I'm figuring this one is easy, but if @adferrand doesn't see the issue right away, LMK and I'll dive in and try to fix.

Seems like it's also related to #362, but until today I would have said that issue was OBE.

**Comment by doddo** [comment]
The breaking of this one seems to correlate with the addition of workarounds for zones with CAA records (#506) (which the API does not support)

```bash
curl -s  -X GET -H "Authorization: sso-key $SSO_KEY" "https://api.godaddy.com/v1/domains/fistofsteel.xyz/records/CAA"  | jq .
{
  "code": "INVALID_VALUE_ENUM",
  "message": "type not any of: A, AAAA, CNAME, MX, NS, SOA, SRV, TXT"
}
```

The error is here in [the provider](https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/godaddy.py#L115). `name` ought to be in the short form but it is not.

        self._put('/domains/{0}/records/{1}/{2}'.format(domain, rtype, name), records)

I stumbled across some other errors too, related to updates throwing 422 expecting a list of records, but getting a single record instead running the test suite after making the above adjustments, which I found a bit confusing as they did not relate to the bits of code which I changed.

Furthermore, the API does now seem to have envolved since the godaddy provider was created, I do believe that it could be simplified somewhat.

Maybe an overhaul of the whole thing could be a good idea?

**Comment by adferrand** [comment]
Hello!

Indeed, I think that replacing `name` with `relative_name` will fix issues. My bad, I missed this during the review of #506.

I just reactivated my domain on godaddy, hope I will be able to resync the test suite and provide a fix in the next hours.

**Comment by adferrand** [comment]
OK. Too much errors. Let's proceed to revert #506.

**Comment by hof** [comment]
Please note that this still not works in `3.3.26`. (after the revert of #506) 

```
bash-5.0# lexicon --version 
lexicon 3.3.26

bash-5.0# lexicon godaddy create "domain.net" TXT --name="foo" --content="bar" --auth-key="x" --auth-secret="x"
Traceback (most recent call last):
  File "/usr/bin/lexicon", line 8, in <module>
...[snip]...
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url:
https://api.godaddy.com/v1/domains/domain.net/records
```
