### ISSUE TITLE
Infoblox Provider - export issue

### ISSUE THREAD

**Issue by Malpractis** [AnalogJ/lexicon#533]
Hey I'm experimenting with dns-lexicon in conjunction with dehydrated using Infoblox.

It looks like the export LEXICON_INFOBLOX_IB_VIEW is not being recognised when using the hook, or when manually exporting and running commands.

This is the error I get when setting the export and running any lexicon command:
Traceback (most recent call last):
  File "/home/test/.local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/home/test/.local/lib/python2.7/site-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/home/test/.local/lib/python2.7/site-packages/lexicon/client.py", line 77, in execute
    self.provider.authenticate()
  File "/home/test/.local/lib/python2.7/site-packages/lexicon/providers/base.py", line 69, in authenticate
    return self._authenticate()
  File "/home/test/.local/lib/python2.7/site-packages/lexicon/providers/infoblox.py", line 85, in _authenticate
    self.domain_id = domains[0]['_ref']
KeyError: 0

However if I just add a --ib-view default into the command it works perfectly.

Any help with this would be most appreciated.

Cheers,
Mal

**Comment by Malpractis** [comment]
Worked around by modifying the hook.
