### ISSUE TITLE
[Patch included] [RESOLVED] easyname dont work anymore AssertionError: Could not find login token.

### ISSUE THREAD

**Issue by Takalele** [AnalogJ/lexicon#624]
Hi,

unfortunately the easyname module stop working, i guess it has something to with some kind of remodeling their webpage especially with the login button and the username field, any ideas?

```
lexicon easyname list domain.xyz.in TXT
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/lexicon/cli.py", line 124, in main
    results = client.execute()
  File "/usr/local/lib/python3.8/dist-packages/lexicon/client.py", line 81, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python3.8/dist-packages/lexicon/providers/base.py", line 74, in authenticate
    return self._authenticate()
  File "/usr/local/lib/python3.8/dist-packages/lexicon/providers/easyname.py", line 63, in _authenticate
    csrf_token = self._get_csrf_token()
  File "/usr/local/lib/python3.8/dist-packages/lexicon/providers/easyname.py", line 365, in _get_csrf_token
    assert csrf_token_field is not None, "Could not find login token."
AssertionError: Could not find login token.
```

BR
Takalele

**Comment by Takalele** [comment]
Hi, 

here is the patch:

```
--- easyname.py 2020-11-07 12:37:09.578889745 +0000
+++ easyname.py.new     2020-11-07 12:47:32.261574534 +0000
@@ -2,6 +2,7 @@
 from __future__ import absolute_import, print_function

 import logging
+import json

 from bs4 import BeautifulSoup, Tag
 from requests import Response, Session
@@ -32,7 +33,9 @@

     URLS = {
         "login": "https://my.easyname.com/en/login",
+        "login_endpoint": "https://my.easyname.com/en/authentication-api/login",
         "domain_list": "https://my.easyname.com/domains/",
+        "dashboard": "https://my.easyname.com/en/dashboard",
         "overview": "https://my.easyname.com/hosting/view-user.php",
         "dns": "https://my.easyname.com/en/domain/dns/index/domain/{}/",
         "dns_create_entry": "https://my.easyname.com/en/domain/dns/create/domain/{}",
@@ -46,20 +49,48 @@
         self.domain_id = None
         self._records = None

-    def _authenticate(self):
-        """
-        Authenticates against Easyname website and try to find out the domain
-        id.
-        Easyname uses a CSRF token in its login form, so two requests are
-        neccessary to actually login.
+    def _get_csrf_token(self):
+        """Return the CSRF Token of easyname login form."""
+        home_response = self.session.get(self.URLS["login"])
+        self._log("Home", home_response)
+        assert home_response.status_code == 200, "Could not load Easyname login page."

-        Returns:
-          bool: True if domain id was found.
+        csrf_token_field = home_response.cookies['CSRF-TOKEN']
+
+        assert csrf_token_field is not None, "Could not find login token."
+        return csrf_token_field
+
+
+    def _login(self, csrf_token):
+        """Attempt to login session on easyname."""
+        payload = {
+                "emailAddress": self._get_provider_option("auth_username"),
+                "password": self._get_provider_option("auth_password")
+        }
+        headers = self.session.headers
+        headers['X-CSRF-TOKEN'] = csrf_token
+
+        login_response = self.session.post(
+            self.URLS["login_endpoint"],
+            data=json.dumps(payload),
+            headers = headers,
+            allow_redirects=True
+        )
+        self._log("Login", login_response)
+        json_response = json.loads(login_response.content)
+        assert (
+            login_response.status_code == 200
+        ), "Could not login due to a network error."
+
+        assert json_response['redirectUrl'] == self.URLS["dashboard"], (
+
+            "Easyname login failed, bad EASYNAME_USER or EASYNAME_PASS.%s"
+            % login_response.url
+            )
+
+
+    def _authenticate(self):

-        Raises:
-          AssertionError: When a request returns unexpected or unknown data.
-          ValueError: When login data is wrong or the domain does not exist.
-        """
         csrf_token = self._get_csrf_token()
         self._login(csrf_token)

@@ -221,15 +252,15 @@
                     rec = {}
                     columns = row.find_all("td")
                     rec["name"] = (columns[0].string or "").strip()
-                    rec["type"] = (columns[1].contents[1] or "").strip()
-                    rec["content"] = (columns[2].string or "").strip()
-                    rec["priority"] = (columns[3].string or "").strip()
-                    rec["ttl"] = (columns[4].string or "").strip()
-                    rec["id"] = int(columns[5].find("a")["href"].rsplit("/", 1)[-1])
-
+                    rec["type"] = (columns[1].contents[1].text or "").strip()
+                    rec["content"] = (columns[2].contents[1].string or "").strip()
+                    rec["priority"] = (columns[3].contents[1].string or "").strip()
+                    rec["ttl"] = (columns[4].contents[1].string or "").strip()
+                    rec["id"] = ""
+                    for a in columns[5].findAll('a', class_="button--naked vers--compact theme--tolerance"):
+                        rec["id"] = a['href'].rsplit("/", 1)[-1]
                     if rec["priority"]:
                         rec["priority"] = int(rec["priority"])
-
                     if rec["ttl"]:
                         rec["ttl"] = int(rec["ttl"])
                 except Exception as error:
@@ -313,11 +344,11 @@

         html = BeautifulSoup(dns_list_response.content, "html.parser")
         self._log("DNS list", html)
-        dns_table = html.find("table", {"id": "cp_domains_dnseintraege"})
+        dns_table = html.find("table")
         assert dns_table is not None, "Could not find DNS entry table"

         def _is_zone_tr(elm):
-            return elm.name.lower() == "tr" and (not elm.has_attr("class"))
+            return elm.name.lower() == "tr" and (elm.has_attr("class"))

         rows = dns_table.findAll(_is_zone_tr)
         assert rows is not None and rows, "Could not find any DNS entries"
@@ -353,37 +384,6 @@
             ]
         return records

-    def _get_csrf_token(self):
-        """Return the CSRF Token of easyname login form."""
-        home_response = self.session.get(self.URLS["login"])
-        self._log("Home", home_response)
-        assert home_response.status_code == 200, "Could not load Easyname login page."
-
-        html = BeautifulSoup(home_response.content, "html.parser")
-        self._log("Home", html)
-        csrf_token_field = html.find("input", {"id": "loginxtoken"})
-        assert csrf_token_field is not None, "Could not find login token."
-        return csrf_token_field["value"]
-
-    def _login(self, csrf_token):
-        """Attempt to login session on easyname."""
-        login_response = self.session.post(
-            self.URLS["login"],
-            data={
-                "username": self._get_provider_option("auth_username") or "",
-                "password": self._get_provider_option("auth_password") or "",
-                "submit": "",
-                "loginxtoken": csrf_token,
-            },
-        )
-        self._log("Login", login_response)
-        assert (
-            login_response.status_code == 200
-        ), "Could not login due to a network error."
-        assert login_response.url == self.URLS["domain_list"], (
-            "Easyname login failed, bad EASYNAME_USER or EASYNAME_PASS.%s"
-            % login_response.url
-        )

     def _get_domain_text_of_authoritative_zone(self):
         """Get the authoritative name zone."""
@@ -396,7 +396,7 @@

         html = BeautifulSoup(zones_response.content, "html.parser")
         self._log("Zone", html)
-        domain_table = html.find("table", {"id": "cp_domain_table"})
+        domain_table = html.find("table")
         assert domain_table is not None, "Could not find domain table"

         # (Sub)domains can either be managed in their own zones or by the
@@ -427,7 +427,7 @@
         try:
             # Hierarchy: TR > TD > SPAN > Domain Text
             tr_anchor = domain_text_element.parent.parent.parent
-            td_anchor = tr_anchor.find("td", {"class": "td_2"})
+            td_anchor = tr_anchor.find("td", {"class": "entity__field taright"})
             link = td_anchor.find("a")["href"]
             domain_id = link.rsplit("/", 1)[-1]
             return domain_id
```

BR
Takalele

**Comment by adferrand** [comment]
Thanks. I will add it for the next release I will do by the end of the week end.

**Comment by adferrand** [comment]
Also, would you have the opportunity to refresh the cassettes stored in the repository to be able to replay the integration tests for the provider?

If so, I will gladly help you in the process.

Otherwise you can also give me privately valid temporary credentials on an account so I can do it myself.

**Comment by Takalele** [comment]
Hi,

Sure - Pull #627 

BR
Takalele
