### ISSUE TITLE
ImportError: No module named transip.client

### ISSUE THREAD

**Issue by tlvince** [AnalogJ/lexicon#63]
Calling `lexicon` throws:

```
Traceback (most recent call last):
  File "/Users/tom/Library/Python/2.7/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==1.1.15', 'console_scripts', 'lexicon')()
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/lexicon/__main__.py", line 49, in main
    parsed_args = MainParser().parse_args()
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/lexicon/__main__.py", line 39, in MainParser
    provider_module = importlib.import_module('lexicon.providers.' + provider)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/lexicon/providers/transip.py", line 3, in <module>
    from transip.client import DomainClient
ImportError: No module named transip.client
```

dns-lexicon (1.1.15)

**Comment by AnalogJ** [comment]
Hey @tlvince 

Sorry about that. I tried to do some magic so that I could support optional libraries for specific providers, but I forgot that the lexicon CLI attempts to load all the providers when it lists the arguments for them. The test suite worked correctly because my optional libraries were present. I'll have to add a new test to ensure that the library works correctly without any optional libraries. 

v1.1.16 was just released and it lets lexicon continue when there's optional libraries missing.

**Comment by AnalogJ** [comment]
Hey @tlvince 
One last thing. Can you confirm that 1.1.16 fixes your issue?

Thanks!

**Comment by tlvince** [comment]
Certainly does! Thanks @AnalogJ
