### ISSUE TITLE
LuaDNS gets 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by mpb159753** [AnalogJ/lexicon#67]
`Namespace(action='create', auth_token='XXXXXXXXXXXXXXXXXXXXXXXX', auth_username='XXXXXXXXXXXXXXXXXXXXXXXX', content='XXXXXXXXXXXXXXXXXXXXXXXX', domain='XXXXXX', identifier=None, name='_XXXXXXXX.', priority=None, provider_name='luadns', ttl=None, type='TXT')

Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==1.1.17', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 52, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 28, in execute
    return self.provider.create_record(self.options.get('type'), self.options.get('name'), self.options.get('content'))
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/luadns.py", line 30, in create_record
    payload = self._post('/zones/{0}/records'.format(self.domain_id), {'type': type, 'name': self._fqdn_name(name), 'content': content, 'ttl': self.options.get('ttl',self.default_ttl)})
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/base.py", line 39, in _post
    return self._request('POST', url, data=data, query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/luadns.py", line 110, in _request
    r.raise_for_status()  # if the request fails for any reason, throw an error.
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request

`

**Comment by mpb159753** [comment]
Luadns  need ttl to

**Comment by AnalogJ** [comment]
Hey @mpb159753 what TTL did you use? Maybe I can set it as the default for that provider

**Comment by mpb159753** [comment]
Sorry, just found the notify, I used 300, seems like you could use any TTL you want can't leave it empty.
