### ISSUE TITLE
Support for Hover accounts with 2FA enabled?

### ISSUE THREAD

**Issue by lksoft** [AnalogJ/lexicon#771]
I realize that the Hover API is not a public one and it may not be possible to implement, but using Hover without 2FA is not feasible for us security-wise, but it would be really useful to be able to use lexicon to be able to at least extract an export.

I have tried connecting with 2FA on and turned off. When off, it worked, with it turned on, I see this:

Traceback (most recent call last):
  File "/home/scott/.local/bin/lexicon", line 8, in <module>
    sys.exit(main())
  File "/home/scott/.local/lib/python3.8/site-packages/lexicon/cli.py", line 124, in main
    results = client.execute()
  File "/home/scott/.local/lib/python3.8/site-packages/lexicon/client.py", line 72, in execute
    self.provider.authenticate()
  File "/home/scott/.local/lib/python3.8/site-packages/lexicon/providers/base.py", line 74, in authenticate
    return self._authenticate()
  File "/home/scott/.local/lib/python3.8/site-packages/lexicon/providers/hover.py", line 47, in _authenticate
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.hover.com/api/login/

Thanks,
Scott

**Comment by prashantsomashekar** [comment]
This would be great to see as well.

Thank you.

**Comment by DVE2000** [comment]
I haven't had issues with getting using the api until probably last month. I had to disable 2FA. I wish they'd let us generate tokens, in a fashion similar to what LIFX does.
