### ISSUE TITLE
Godaddy list records not working

### ISSUE THREAD

**Issue by samcro1967** [AnalogJ/lexicon#823]
Just stumbled across this today and am looking to use this to maintain A records hosted by Goadddy.  I get an error after I installed trying to list the A records.  I also tried other records types and get the same result.

**Installed using this command**
```
pip install git+https://github.com/AnalogJ/lexicon.git
```

**Command executed**
```
set auth_key=<my_key>
set auth_secret=<my_secret>
lexicon godaddy list mydomain.net A
```

**Error Message**
```
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python37\Scripts\lexicon.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\lexicon\cli.py", line 131, in main
    results = client.execute()
  File "c:\python37\lib\site-packages\lexicon\client.py", line 79, in execute
    self.provider.authenticate()
  File "c:\python37\lib\site-packages\lexicon\providers\base.py", line 73, in authenticate
    self._authenticate()
  File "c:\python37\lib\site-packages\lexicon\providers\godaddy.py", line 56, in _authenticate
    result = self._get(f"/domains/{domain}")
  File "c:\python37\lib\site-packages\lexicon\providers\base.py", line 173, in _get
    return self._request("GET", url, query_params=query_params)
  File "c:\python37\lib\site-packages\lexicon\providers\godaddy.py", line 300, in _request
    allowed_methods=frozenset(["GET", "PUT", "POST", "DELETE", "PATCH"]),
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

**Comment by adferrand** [comment]
Lexicon 3.6.1 (https://github.com/AnalogJ/lexicon/releases/tag/v3.6.1) should have fixed the issue. Can you confirm @samcro1967 ?
