### ISSUE TITLE
GratisDNS provider doesn't work

### ISSUE THREAD

**Issue by Roensby** [AnalogJ/lexicon#991]
As far as I can see, GratisDNS doesn't have an api, so `gratisdns.py` simply navigates the web admin interface.
Unfortunately, they seem to have changed their html since `gratisdns.py` was written, as the provider integration fails with the following error output:

```
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
Requesting a certificate for *.example.domain and example.domain
Hook '--manual-auth-hook' for example.domain reported error code 1
Hook '--manual-auth-hook' for example.domain ran with error output:
 Error while executing the `auth` hook:
 Domain example.domain not found
 Traceback (most recent call last):
   File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 40, in main
     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
   File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 61, in auth
     txt_challenge(certificate, profile, token, domain, action="create")
   File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/challenge.py", line 57, in txt_challenge
     Client(lexicon_config).execute()
   File "/opt/dnsrobocert/lib/python3.9/site-packages/lexicon/client.py", line 79, in execute
     self.provider.authenticate()
   File "/opt/dnsrobocert/lib/python3.9/site-packages/lexicon/providers/base.py", line 73, in authenticate
     self._authenticate()
   File "/opt/dnsrobocert/lib/python3.9/site-packages/lexicon/providers/gratisdns.py", line 60, in _authenticate
     raise AuthenticationError(f"Domain {self.domain} not found")
 lexicon.exceptions.AuthenticationError: Domain example.domain not found
 ```

**Comment by Roensby** [comment]
My mistake, probably due to mistyped auth credentials
